language: node_js
node_js:
  - "node"
notifications:
  email:
    on_success: never
    on_failure: always
  
# Cache node_modules and typings for future runs. This does make the builds
# sometimes fail because of a bad cache but usually this is a huge test
# performance win.
cache: 
  yarn: true
  directories:
    - typings
  
script:
  - npm run lint && npm run build && npm run test
after_success:
  - npm run semantic-release