language: node_js
node_js:
  - "node"
notifications:
  email:
    on_success: never
    on_failure: always
  
cache: 
  yarn: true
  directories:
    - typings
  
script:
  - npm run run-script
after_success:
  - npm run semantic-release